### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bobronium/Preferences/com.apple.SocialLayer.plist'

### ISSUE THREAD

**Issue by Bobronium** [Tatsh/macprefs#2]
```py
~
$ prefs-export
Traceback (most recent call last):
  File "/Users/bobronium/.local/bin/prefs-export", line 8, in <module>
    sys.exit(main())
  File "/Users/bobronium/.local/pipx/venvs/macprefs/lib/python3.10/site-packages/macprefs/command.py", line 207, in main
    ret = loop.run_until_complete(
  File "/Users/bobronium/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/bobronium/.local/pipx/venvs/macprefs/lib/python3.10/site-packages/macprefs/command.py", line 97, in _main
    all_data.extend(await asyncio.gather(*export_tasks))
  File "/Users/bobronium/.local/pipx/venvs/macprefs/lib/python3.10/site-packages/macprefs/command.py", line 62, in _defaults_export
    with plist_out.open('rb') as f:
  File "/Users/bobronium/.pyenv/versions/3.10.1/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bobronium/Preferences/com.apple.SocialLayer.plist'
```

`prefs-export -o <path>` works fine
If I manually create Preferences folder before running bare `prefs-export`, it works.

**Comment by Tatsh** [comment]
Please try with the latest push and report back (and close this issue if it is resolved). I'll make a new release later.

**Comment by Tatsh** [comment]
Fully resolved with https://github.com/Tatsh/macprefs/commit/c9700e2eddf82ecac61a90d7ca3e7dc439ef325f
